FROM debian:13-slim

ARG TOOLBOX_VERSION=16-2-671

RUN grep -q non-free /etc/apt/sources.list.d/debian.sources || sed -i 's,main,main contrib non-free,' /etc/apt/sources.list.d/debian.sources

RUN --mount=type=cache,target=/var/cache/apt \
        apt-get update -y && apt-get upgrade -y \
        && apt-get install -y  \
                apt-utils  \
                procps \
                net-tools \
                fontconfig  \
                fonts-dejavu \
                libatomic1 \
                tini


# avoid installing the full /usr/bin/lsb_release package, which can be several megabytes in size. Use a lightweight mock implementation instead.
COPY lsb_release_mockup.sh /usr/bin
RUN test -x /usr/bin/lsb_release || ln -s /usr/bin/lsb_release_mockup.sh  /usr/bin/lsb_release

# optional - install microsoft truetype fonts ...
# RUN --mount=type=cache,target=/var/cache/apt apt-get install -y ttf-mscorefonts-installer

# optional - install libreoffice (only needed to convert office documents to pdf). Note: this adds nearly 700MB to the image ...
# RUN --mount=type=cache,target=/var/cache/apt apt-get install -y --no-install-recommends libreoffice-nogui liblibreoffice-java default-jre-headless

COPY callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION} /opt/callas/callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION}

# add some "convenience" symlinks ...
RUN mkdir -p /opt/callas && cd /opt/callas && ln -s callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION} pdftoolbox-cli && ln -s callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION} cli

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN useradd -m callas
USER callas

WORKDIR /opt/callas/callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION}

# long: https://www.bmc.com/blogs/docker-cmd-vs-entrypoint/
# short ...
#   ENTRYPOINT specifies default parameters that cannot be overridden. It can be used for initial setup. Here `tini` does all this complicated PID1 signal handling stuff for us
#   CMD specifies default parameters that can be overridden. By using ENTRYPOINT *and* CMD together we get the best from both worlds

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/bin/bash"]


