FROM opensuse/leap:15.6

RUN zypper update -y && \
    zypper install -y fontconfig glibc-locale dejavu-fonts procps which psutils

# avoid installing the full /usr/bin/lsb_release package, which can be several megabytes in size. Use a lightweight mock implementation instead.
COPY lsb_release_mockup.sh /usr/bin
RUN test -x /usr/bin/lsb_release || ln -s /usr/bin/lsb_release_mockup.sh  /usr/bin/lsb_release

# optional - install microsoft truetype fonts ...
# RUN zypper install -y fetchmsttfonts

# optional - install libreoffice (only needed to convert office documents to pdf). Note: this adds nearly 500MB to the image ...
# RUN zypper install -y libreoffice-officebean libreoffice-writer libreoffice-writer-extensions libreoffice-calc libreoffice-calc-extensions libreoffice-impress libreoffice-draw

COPY callas_pdfToolboxCLI_Linux_16-0-657 /opt/callas/callas_pdfToolboxCLI_Linux_16-0-657
# remove some incompatible libs (libstdc++.so.6)
RUN find /opt/callas/callas_pdfToolboxCLI_Linux_16-0-657 -type l -name libstdc++.so.6 -exec rm {} +

# add some "convenience" symlinks ...
RUN cd /opt/callas && ln -s callas_pdfToolboxCLI_Linux_16-0-657 pdftoolbox-cli && ln -s callas_pdfToolboxCLI_Linux_16-0-657 cli


WORKDIR /opt/callas/callas_pdfToolboxCLI_Linux_16-0-657

