FROM opensuse/leap:15.6

RUN zypper update -y && \
    zypper install -y lsb-release fontconfig glibc-locale dejavu-fonts procps which psutils


# optional - install microsoft truetype fonts ...
# RUN zypper install -y fetchmsttfonts

# optional - install libreoffice (only needed to convert office documents to pdf). Note: this adds nearly 500MB to the image ...
# RUN zypper install -y libreoffice-officebean libreoffice-writer libreoffice-writer-extensions libreoffice-calc libreoffice-calc-extensions libreoffice-impress libreoffice-draw

COPY callas_pdfToolboxCLI_x64_Linux_15-2-646-1 /opt/callas/callas_pdfToolboxCLI_x64_Linux_15-2-646-1
# remove some incompatible libs (libstdc++.so.6)
RUN find /opt/callas/callas_pdfToolboxCLI_x64_Linux_15-2-646-1 -type l -name libstdc++.so.6 -exec rm {} +

# add some "convenience" symlinks ...
RUN cd /opt/callas && ln -s callas_pdfToolboxCLI_x64_Linux_15-2-646-1 pdftoolbox-cli && ln -s callas_pdfToolboxCLI_x64_Linux_15-2-646-1 cli


WORKDIR /opt/callas/callas_pdfToolboxCLI_x64_Linux_15-2-646-1

