FROM almalinux:9.5

RUN dnf update -y && \
    dnf install -y fontconfig which libfontenc glibc-gconv-extra dejavu-sans-fonts dejavu-sans-mono-fonts dejavu-serif-fonts


# optional - install microsoft truetype fonts ...
# RUN dnf install https://rpmfind.net/linux/dag/redhat/el7/en/x86_64/dag/RPMS/cabextract-1.4-1.el7.rf.x86_64.rpm && \
#    dnf install https://rpmfind.net/linux/almalinux/9.5/devel/x86_64/os/Packages/xorg-x11-font-utils-7.5-53.el9.x86_64.rpm && \
#    dnf install https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm

# optional - install libreoffice (only needed to convert office documents to pdf). Note: this adds nearly 500MB to the image ...
# RUN dnf install -y libreoffice

COPY callas_pdfToolboxCLI_x64_Linux_15-2-646 /opt/callas/callas_pdfToolboxCLI_x64_Linux_15-2-646

# add some "convenience" symlinks ...
RUN cd /opt/callas && ln -s callas_pdfToolboxCLI_x64_Linux_15-2-646 pdftoolbox-cli && ln -s callas_pdfToolboxCLI_x64_Linux_15-2-646 cli

# almalinux does not have /usr/bin/lsb_release. use a mockup instead
COPY lsb_release_mockup.sh /usr/bin
RUN test -x /usr/bin/lsb_release || ln -s /usr/bin/lsb_release_mockup.sh  /usr/bin/lsb_release

WORKDIR /opt/callas/callas_pdfToolboxCLI_x64_Linux_15-2-646

