# FROM redhat/ubi9:9.6
FROM redhat/ubi9

ARG TOOLBOX_VERSION=16-2-671

RUN dnf update -y && \
    dnf install -y procps fontconfig which libfontenc glibc-gconv-extra dejavu-sans-fonts dejavu-sans-mono-fonts dejavu-serif-fonts libatomic \
        && cd /usr/lib64 && { test -f libbz2.so.1.0 || ln -s libbz2.so.1 libbz2.so.1.0; }

# avoid installing the full /usr/bin/lsb_release package, which can be several megabytes in size. Use a lightweight mock implementation instead.
COPY lsb_release_mockup.sh /usr/bin
RUN test -x /usr/bin/lsb_release || ln -s /usr/bin/lsb_release_mockup.sh  /usr/bin/lsb_release

# optional - install microsoft truetype fonts ...

# RUN dnf install mkfontscale \
#    && dnf install https://www.cabextract.org.uk/cabextract-1.11-1.x86_64.rpm \
#    && dnf install https://rpmfind.net/linux/fedora/linux/releases/39/Everything/x86_64/os/Packages/x/xorg-x11-font-utils-7.5-56.fc39.x86_64.rpm \
#    && dnf install https://rpmfind.net/linux/sourceforge/m/ms/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm

# optional - install libreoffice (only needed to convert office documents to pdf). Note: this adds nearly 500MB to the image ...
# RUN dnf install -y libXinerama cairo cups-libs libSM java
# RUN cd /root && curl -LO https://download.documentfoundation.org/libreoffice/stable/25.2.4/rpm/x86_64/LibreOffice_25.2.4_Linux_x86-64_rpm.tar.gz \
#      && tar xvpf LibreOffice_25.2.4_Linux_x86-64_rpm.tar.gz \
#      && cd LibreOffice_25.2.4.3_Linux_x86-64_rpm/RPMS \
#      && rpm -Uvh *.rpm && cd /usr/bin && ln -s /opt/libreoffice25.2/program/soffice

COPY callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION} /opt/callas/callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION}

# add some "convenience" symlinks ...
RUN mkdir -p /opt/callas && cd /opt/callas && ln -s callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION} pdftoolbox-cli && ln -s callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION} cli

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# install `tini` - as needed by the ENTRYPOINT
ARG TARGETARCH
ENV TINI_VERSION=v0.19.0
RUN curl -L -o /usr/local/bin/tini https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${TARGETARCH} && chmod +x /usr/local/bin/tini

RUN useradd -m callas
USER callas

WORKDIR /opt/callas/callas_pdfToolboxCLI_Linux_${TOOLBOX_VERSION}

# long: https://www.bmc.com/blogs/docker-cmd-vs-entrypoint/
# short ...
#   ENTRYPOINT specifies default parameters that cannot be overridden. It can be used for initial setup. Here `tini` does all this complicated PID1 signal handling stuff for us
#   CMD specifies default parameters that can be overridden. By using ENTRYPOINT *and* CMD together we get the best from both worlds
ENTRYPOINT ["/usr/local/bin/tini", "--"]
CMD ["/bin/bash"]

