# note: for multistage builds see https://docs.docker.com/develop/develop-images/multistage-build

FROM debian

# note: see README.md regarding howto get and prepare (aka modify) callas_pdfEngineSDK_16-0-657 for usage within a container environment

COPY callas_pdfEngineSDK_16-0-657 /opt/callas/callas_pdfEngineSDK_16-0-657

# avoid installing the full /usr/bin/lsb_release package, which can be several megabytes in size. Use a lightweight mock implementation instead.
COPY lsb_release_mockup.sh /usr/bin
RUN test -x /usr/bin/lsb_release || ln -s /usr/bin/lsb_release_mockup.sh  /usr/bin/lsb_release

# add some "convenience" symlinks ...
RUN cd /opt/callas && ln -s callas_pdfEngineSDK_16-0-657 callas-sdk && ln -s callas_pdfEngineSDK_16-0-657 sdk 
RUN apt-get update -y && apt-get upgrade -y \
        && apt-get install -y  \
                apt-utils  \
                locales \
                procps \
                net-tools \
                fontconfig  \
                fonts-dejavu \
                libatomic1 \
        && echo "C.UTF-8 UTF-8" > /etc/locale.gen && locale-gen && update-locale LANG=C.UTF-8 && apt-get purge -y locales && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

# optional - install microsoft truetype fonts ...
# RUN sed -i 's,main,main contrib non-free non-free-firmware,' /etc/apt/sources.list.d/debian.sources
# RUN apt-get install -y ttf-mscorefonts-installer

# optional - install libreoffice (only needed to convert office documents to pdf). Note: this adds nearly 700MB to the image ...
# RUN apt-get install --no-install-recommends libreoffice liblibreoffice-java default-jre-headless
          
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8


# optional - install microsoft truetype fonts ...
# RUN apt-get install -y ttf-mscorefonts-installer


WORKDIR /opt/callas/callas_pdfEngineSDK_16-0-657/sample-C/unix
