FROM debian:13-slim

ARG PDFENGINE_VERSION=17-0-683

RUN grep -q non-free /etc/apt/sources.list.d/debian.sources || sed -i 's,main,main contrib non-free,' /etc/apt/sources.list.d/debian.sources

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN apt-get update -y && apt-get upgrade -y \
        && apt-get install -y  \
                apt-utils  \
                locales \
                procps \
                net-tools \
                fontconfig  \
                fonts-dejavu \
                libatomic1 \
                tini \
        && echo "C.UTF-8 UTF-8" > /etc/locale.gen && locale-gen && update-locale

# avoid installing the full /usr/bin/lsb_release package, which can be several megabytes in size. Use a lightweight mock implementation instead.
COPY lsb_release_mockup.sh /usr/bin
RUN test -x /usr/bin/lsb_release || ln -s /usr/bin/lsb_release_mockup.sh  /usr/bin/lsb_release

# optional - install microsoft truetype fonts ...
# RUN apt-get install -y ttf-mscorefonts-installer

# optional - install libreoffice (only needed to convert office documents to pdf). Note: this adds nearly 700MB to the image ...
# RUN apt-get install -y --no-install-recommends libreoffice-nogui libreoffice-script-provider-python

COPY callas_pdfEngineSDK_${PDFENGINE_VERSION} /opt/callas/callas_pdfEngineSDK_${PDFENGINE_VERSION}
# add some "convenience" symlinks ...
RUN cd /opt/callas && ln -s callas_pdfEngineSDK_${PDFENGINE_VERSION} callas-sdk && ln -s callas_pdfEngineSDK_${PDFENGINE_VERSION} sdk

WORKDIR /opt/callas/callas_pdfEngineSDK_${PDFENGINE_VERSION}/sample-C/unix

# long: https://www.bmc.com/blogs/docker-cmd-vs-entrypoint/
# short ...
#   ENTRYPOINT specifies default parameters that cannot be overridden. It can be used for initial setup. Here `tini` does all this complicated PID1 signal handling stuff for us
#   CMD specifies default parameters that can be overridden. By using ENTRYPOINT *and* CMD together we get the best from both worlds

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/bin/bash"]

# long: https://www.bmc.com/blogs/docker-cmd-vs-entrypoint/
# short ...
#   ENTRYPOINT specifies default parameters that cannot be overridden. It can be used for initial setup. Here `tini` does all this complicated PID1 signal handling stuff for us
#   CMD specifies default parameters that can be overridden. By using ENTRYPOINT *and* CMD together we get the best from both worlds

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/bin/bash"]
